### ISSUE TITLE
error: 'class IPAddress' has no member named 'from_ip_addr_t'

### ISSUE THREAD

**Issue by DaeMonSxy** [mathieucarbou/AsyncTCP#13]
Probably and update for espressif32 stable would be required
```
 platform =
        espressif32 ;stable
```

```
In member function 'bool AsyncClient::connect(const IPAddress&, uint16_t)':
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp:736:8: error: 'const class IPAddress' has no member named 'to_ip_addr_t'
  736 |     ip.to_ip_addr_t(&addr);
      |        ^~~~~~~~~~~~
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp: In member function 'void AsyncClient::_dns_found(ip_addr*)':
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp:1054:12: error: 'class IPAddress' has no member named 'from_ip_addr_t'
 1054 |         ip.from_ip_addr_t(ipaddr);
      |            ^~~~~~~~~~~~~~
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp: In member function 'IPAddress AsyncClient::remoteIP6()':
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp:1199:8: error: 'class IPAddress' has no member named 'from_ip_addr_t'
 1199 |     ip.from_ip_addr_t(&(_pcb->remote_ip));
      |        ^~~~~~~~~~~~~~
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp: In member function 'IPAddress AsyncClient::localIP6()':
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp:1208:8: error: 'class IPAddress' has no member named 'from_ip_addr_t'
 1208 |     ip.from_ip_addr_t(&(_pcb->local_ip));
      |        ^~~~~~~~~~~~~~
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp: In member function 'IPAddress AsyncClient::remoteIP()':
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp:1247:8: error: 'class IPAddress' has no member named 'from_ip_addr_t'
 1247 |     ip.from_ip_addr_t(&(_pcb->remote_ip));
      |        ^~~~~~~~~~~~~~
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp: In member function 'IPAddress AsyncClient::localIP()':
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp:1264:8: error: 'class IPAddress' has no member named 'from_ip_addr_t'
 1264 |     ip.from_ip_addr_t(&(_pcb->local_ip));
      |        ^~~~~~~~~~~~~~
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp: In member function 'void AsyncServer::begin()':
/platformio_libdeps/ESP32/Async TCP/src/AsyncTCP.cpp:1478:11: error: 'class IPAddress' has no member named 'to_ip_addr_t'
 1478 |     _addr.to_ip_addr_t(&local_addr);
      |           ^~~~~~~~~~~~
*** [/0_iqHome_firmware/ESP32/lib8fa/Async TCP/AsyncTCP.cpp.o] Error 1
```

ps: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
seems to be compiling well.

**Comment by mathieucarbou** [comment]
Hello,

Can you please point me to the [platform package specification section](https://docs.platformio.org/en/latest/projectconf/sections/env/options/platform/platform.html) which documents the usage of `; stable` to point to a stable version ?

Project contains CI: it is compiled on both arduino 2, 3 and latest platform. 

If you want to point to a stable version, please follow espressif guidelines

```
[env:arduino]
platform = espressif32
board = esp32dev

[env:arduino-2]
platform = espressif32@6.7.0
board = esp32dev

[env:arduino-3]
platform = espressif32
platform_packages=
  platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
  platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip
board = esp32dev
```

**Comment by DaeMonSxy** [comment]
**platformio.ini**

`[env:ESP32]

    upload_speed = 460800
    monitor_speed = 115200
    
    monitor_filters =  
        esp32_exception_decoder     ;Custom filter for Espressif 32 which decodes crash exception
    
    build_type = debug
    ;build_type = release
    
    ;debug_tool = esp-prog

    board = wemos_d1_mini32

    upload_protocol = esptool
    ;upload_protocol = esp-prog
    
    framework = 
        arduino
        ;espidf
        
    platform =
        ;espressif32 ;stable
        https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
        
    ;lib_compat_mode = soft
    lib_compat_mode = strict

    lib_deps =
        SPI
        
        ; All
            paulstoffregen/Time ; date-time
            ;https://github.com/bblanchon/ArduinoJson
            https://github.com/bblanchon/ArduinoJson/archive/refs/tags/v6.21.3.zip ; 2023-07-23
            https://github.com/adafruit/Adafruit_NeoPixel
            ;https://github.com/adafruit/Adafruit_NeoPixel/archive/refs/tags/1.12.2.zip ;2024.05.07
            https://github.com/marvinroger/async-mqtt-client 
        
        ; me-no-dev
            ;https://github.com/me-no-dev/AsyncTCP
            ;https://github.com/me-no-dev/ESPAsyncWebServer
            ;https://github.com/me-no-dev/ESPAsyncTCP
            ;https://github.com/me-no-dev/ESPAsyncUDP

        ; mathieucarbou
            ;https://github.com/mathieucarbou/AsyncTCP
            ;https://github.com/mathieucarbou/AsyncTCP/archive/refs/tags/v3.1.4.zip
            https://github.com/mathieucarbou/ESPAsyncWebServer ;  library.json dependency- AsyncTCP
            ;https://github.com/mathieucarbou/MycilaMQTT
            ;https://github.com/mathieucarbou/WebSerialLite
        
    build_flags =
        -g 
        -w -Wextra -Wpedantic ;compiler's warning level using the -w flag to suppress warnings or -W flags to enable specific warning categories
        -ggdb                       ; Enable debugging symbols for use with GDB
        -Og                         ; Optimize for debugging, suitable for debugging with line numbers
        -g3                         ; Include extensive debugging information in the compiled binary
        ;-Os                         ; Optimize for size (Smallest code size)
        -Wl,--print-memory-usage    ; Print memory usage information after the build
        -std=c++11
        -DCONFIG_FREERTOS_UNICORE=1
        -D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
        
        -DCORE_DEBUG_LEVEL=0 ; None
        ;-DCORE_DEBUG_LEVEL=1 ; Error
        ;-DCORE_DEBUG_LEVEL=2 ; Warn
        ;-DCORE_DEBUG_LEVEL=3 ; Info
        ;-DCORE_DEBUG_LEVEL=4 ; Debug (verbose)
        ;-DCORE_DEBUG_LEVEL=5  ; Verbose
        
        ;-DARDUINOJSON_DEBUG=1                 ; Enable debug mode in ArduinoJSON
        -DARDUINOJSON_ENABLE_ARDUINO_STRING=0 ; Disable Arduino String in ArduinoJSON
        -DARDUINOJSON_ENABLE_STD_STRING=1     ; Enable std::string in ArduinoJSON
        -DARDUINOJSON_USE_LONG_LONG=1         ; Enable long long in ArduinoJSON
        -DARDUINOJSON_USE_DOUBLE=1            ; Enable double in ArduinoJSON
        ;-DARDUINOJSON_STRING_BUFFER_SIZE=32   ; Set the ArduinoJSON string buffer size
        -DARDUINOJSON_ENABLE_COMMENTS=0       ; Disable comments in ArduinoJSON
        ;-DARDUINOJSON_ENABLE_NAN=1            ; Enable support for NaN (Not-a-Number) in ArduinoJSON
        ;-DARDUINOJSON_ENABLE_INFINITY=1       ; Enable support for Infinity in ArduinoJSON
        ;-DARDUINOJSON_ENABLE_STD_STREAM=1     ; Enable support for std::istream and std::ostream in ArduinoJSON
        ;-DARDUINOJSON_STRING_BUFFER_SIZE=32   ; Set the ArduinoJSON string buffer size to any positive integer
        ;-DARDUINOJSON_HAS_NULLPTR=1           ; Enable support for nullptr in ArduinoJSON
        -DARDUINOJSON_ENABLE_PROGMEM=1        ; Enable PROGMEM (Program Memory) support in ArduinoJSON
        ;-DARDUINOJSON_ENABLE_ARDUINO_PRINT=0  ; Disable Arduino Print support in ArduinoJSON

        -D CONFIG_ASYNC_TCP_QUEUE_SIZE=128 ;Async TCP queue size
        -D CONFIG_ASYNC_TCP_RUNNING_CORE=1 ; Async TCP async task core
        -D CONFIG_ASYNC_TCP_STACK_SIZE=8096 ; Async TCP async stac ksize
        -D WS_MAX_QUEUED_MESSAGES=64 ; WebSocket queue size
        `

**compile without issues**:
` platform =
        ;espressif32 ;stable
        https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip`

**compile error**:
` platform =
        espressif32 ;stable
        ;https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip`
output:
`/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:79:8: error: 'xQueueHandle' does not name a type; did you mean 'QueueHandle_t'?
   79 | static xQueueHandle _async_queue;
      |        ^~~~~~~~~~~~
      |        QueueHandle_t
Compiling /Users/xy/0_iqHome_firmware/ESP32/lib84b/AsyncMqttClient/AsyncMqttClient/Packets/Out/Publish.cpp.o
Compiling /Users/xy/0_iqHome_firmware/ESP32/lib84b/AsyncMqttClient/AsyncMqttClient/Packets/Out/Subscribe.cpp.o
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp: In function 'bool _init_async_event_queue()':
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:97:9: error: '_async_queue' was not declared in this scope
   97 |     if(!_async_queue){
      |         ^~~~~~~~~~~~
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp: In function 'bool _send_async_event(lwip_event_packet_t**)':
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:107:12: error: '_async_queue' was not declared in this scope
  107 |     return _async_queue && xQueueSend(_async_queue, e, portMAX_DELAY) == pdPASS;
      |            ^~~~~~~~~~~~
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp: In function 'bool _prepend_async_event(lwip_event_packet_t**)':
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:111:12: error: '_async_queue' was not declared in this scope
  111 |     return _async_queue && xQueueSendToFront(_async_queue, e, portMAX_DELAY) == pdPASS;
      |            ^~~~~~~~~~~~
Compiling /Users/xy/0_iqHome_firmware/ESP32/lib84b/AsyncMqttClient/AsyncMqttClient/Packets/Out/Unsubscribe.cpp.o
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp: In function 'bool _get_async_event(lwip_event_packet_t**)':
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:115:12: error: '_async_queue' was not declared in this scope
  115 |     return _async_queue && xQueueReceive(_async_queue, e, portMAX_DELAY) == pdPASS;
      |            ^~~~~~~~~~~~
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp: In function 'bool _remove_events_with_arg(void*)':
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:122:9: error: '_async_queue' was not declared in this scope
  122 |     if(!_async_queue){
      |         ^~~~~~~~~~~~
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:127:26: error: '_async_queue' was not declared in this scope
  127 |         if(xQueueReceive(_async_queue, &first_packet, 0) != pdPASS){
      |                          ^~~~~~~~~~~~
Compiling /Users/xy/0_iqHome_firmware/ESP32/lib84b/AsyncMqttClient/AsyncMqttClient/Packets/PingRespPacket.cpp.o
In file included from /Users/xy/platformio_packages/framework-arduinoespressif32@src-1f82e173e856151a94dfccf0eca41582/tools/esp32-arduino-libs/esp32/include/freertos/FreeRTOS-Kernel/include/freertos/semphr.h:42,
                 from /Users/xy/platformio_packages/framework-arduinoespressif32@src-1f82e173e856151a94dfccf0eca41582/cores/esp32/Arduino.h:35,
                 from /Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:22:
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:135:30: error: '_async_queue' was not declared in this scope
  135 |         } else if(xQueueSend(_async_queue, &first_packet, portMAX_DELAY) != pdPASS){
      |                              ^~~~~~~~~~~~
/Users/xy/platformio_packages/framework-arduinoespressif32@src-1f82e173e856151a94dfccf0eca41582/tools/esp32-arduino-libs/esp32/include/freertos/FreeRTOS-Kernel/include/freertos/queue.h:545:26: note: in definition of macro 'xQueueSend'
  545 |     xQueueGenericSend( ( xQueue ), ( pvItemToQueue ), ( xTicksToWait ), queueSEND_TO_BACK )
      |                          ^~~~~~
/Users/xy/platformio_libdeps/ESP32/AsyncTCP/src/AsyncTCP.cpp:140:22: error: '_async_queue' was not declared in this scope
  140 |     while(xQueuePeek(_async_queue, &packet, 0) == pdPASS && packet != first_packet){
      |                      ^~~~~~~~~~~~
*** [/Users/xy/0_iqHome_firmware/ESP32/lib959/AsyncTCP/AsyncTCP.cpp.o] Error 1`

**Comment by mathieucarbou** [comment]
@DaeMonSxy : you didn't answer my question...
Use: `platform = espressif32@6.7.0`

**Comment by DaeMonSxy** [comment]
I believe, I have answered above.

well, thats the same.

platform = espressif32@6.7.0 
=
platform = https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip

thats fine, compile went well.
but with platform = espressif32, so latest espressif32 having issues.

**Comment by mathieucarbou** [comment]
Are you having a cache issue ? The CI is passing correctly with all the combinations below.

`platform = espressif32@6.7.0`

`platform = espressif32`

```
platform_packages=
  platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
  platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip
```
