### ISSUE TITLE
[Q] async http request - built on asyncTCP

### ISSUE THREAD

**Issue by DaeMonSxy** [mathieucarbou/AsyncTCP#19]
Hi there,

I been using your forked lib for a while now, 
still, cannot figure out the issue.
I have a library to create http requests, and as response work with that.
It seems, sometimes I an send more than 5000 requests, the code stable for days, but sometimes it is crashing/restarting/freezing in 1-2 days.

any hints are appreciated, thanks

Library: [https://github.com/DaeMonSxy/asynchttprequest](https://github.com/DaeMonSxy/asynchttprequest)

**Comment by mathieucarbou** [comment]
Hello,
I am sorry I do not have any hint to offer.
You would need to find a way to monitor heap, stack, save crash dump and analyse it, etc.
Once you'll have more data, you will see if the issue is related to this lib and if yes you will be able to post here to complete.
